language: ruby
rvm:
- 2.2

install: bundle install
script: bundle exec jekyll build

# branch whitelist
branches:
  only:
  - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
