# Site settings
title: Miles.ink
email: miles@milesrausch.com
description: >
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
url: "http://miles.ink"
twitter_username: awayken
github_username:  awayken

# Build settings
markdown: kramdown

# Kramdown settings
kramdown:
  input: GFM

exclude: [vendor]
