# Site settings
title: Miles.ink
email: miles@milesrausch.com
description: >
  A ways to go before it dries.
baseurl: ""
url: "http://miles.ink"
twitter_username: awayken
github_username:  awayken

# Build settings
markdown: kramdown

# Kramdown settings
kramdown:
  input: GFM

exclude: [vendor]
